server:
  id: 2
  key: 'Rushu'

network:
  game:
    port: 8788
    ip: '127.0.0.1'
  exchange:
    timeout: 5
    port: 8787
    ip: '127.0.0.1'

database:
  login:
    host: 'localhost'
    user: 'grandnainconnu'
    password: ''
    name: 'hetwan_login'
  game:
    host: 'localhost'
    user: 'grandnainconnu'
    password: ''
    name: 'hetwan_game'
