server:
  id: 1
  key: 'test'

network:
  game:
    port: 8788
    ip: '127.0.0.1'
  exchange:
    port: 8787
    ip: '127.0.0.1'

database:
  login:
    user: 'root'
    password: ''
    name: 'hetwan'
  game:
    user: 'root'
    password: ''
    name: 'hetwan-game'